# =========================
# Site Metadata
# =========================
title: "Overdrive Wiki"
description: "Overdrive Wiki是一个由社区共同维护的百科全书项目"
url: "https://overdrive-wiki.pages.dev"
favicon_path: assets/favicon.ico


# =========================
# Theme & Plugins
# =========================
remote_theme: sighingnow/jekyll-gitbook

plugins:
  - jekyll-remote-theme
  - jekyll-toc


# =========================
# Markdown & Syntax Highlight
# =========================
markdown: kramdown

markdown_ext: markdown,mkdown,mkdn,mkd,md

kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: true
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful


# =========================
# Table of Contents
# =========================
toc:
  enabled: true
  h_min: 1
  h_max: 3


# =========================
# URL & Permalink
# =========================
permalink: /:title/


# =========================
# Collections
# =========================
collections:
  index:
    output: true
    permalink: /index/:title/

  drug:
    output: true
    permalink: /drug/:title/

  other:
    output: true
    permalink: /other/:title/


# GitBook 左侧导航
ordered_collections:
  - index


# =========================
# Defaults
# =========================
defaults:
  - scope:
      path: ""
      type: index
    values:
      layout: home

  - scope:
      path: ""
    values:
      layout: post


# =========================
# Include Files
# =========================
include:
  - _redirects
